# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inspiration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Full_text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_text_value', models.CharField(max_length=1000)),
                ('author_name_text_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspiration.Author_Name')),
            ],
        ),
    ]
